version: 0.1
environment_variables:
    plaintext:
        S3_BUCKET: "caturday.joshuagruber.com"
        BUILD_ENV: "prod"
        CHROME_BIN: "chromium-browser"

phases:
  install:
    commands:
      - echo "nothing to do in install"
  pre_build:
    commands:
      - echo "Installing dependencies - `pwd`"
      - node --version
      - apt-get update && apt-get -y install chromium-browser
      - cd app && npm install && npm install -g serverless typescript && serverless package
      - cd frontend && npm install && npm install -g @angular/cli && npm i -g phantomjs-prebuilt
      - echo "dependencies install completed `date`"
  build:
    commands:
      - echo "Starting build `date` in `pwd`"
      - aws cloudformation package --template-file ./app/.serverless/cloudformation-template-update-stack.json --s3-bucket $BUILD_OUTPUT_BUCKET --output-template-file app-output_sam.yaml
      - echo "starting Angular build"
      - cd frontend && ng test --single-run --progress false --log-level verbose
      - cd frontend && ng build --env=${BUILD_ENV}

  post_build:
    commands:
      - echo "build completed on `date`"

artifacts:
  files:
    - app-output_sam.yaml
  discard-paths: yes
