version: 0.1

phases:
  install:
    commands:
      - echo "nothing to do in install"
  pre_build:
    commands:
      - echo "Installing dependencies - `pwd`"
      - node --version
      - cd app && npm install
      - cd frontend && npm install &&  npm install -g @angular/cli
      - echo "dependencies install completed `date`"
  build:
    commands:
      - echo "Starting build `date` in `pwd`"
      - aws cloudformation package --template-file app-sam.yaml --s3-bucket $BUILD_OUTPUT_BUCKET --output-template-file app-output_sam.yaml
      - aws cloudformation package --template-file test-sam.yaml --s3-bucket $BUILD_OUTPUT_BUCKET --output-template-file test-output_sam.yaml
      - echo "starting Angular build"
      - cd frontend && ng test --single-run
      - cd frontend && ng build --env=${BUILD_ENV}

  post_build:
    commands:
      - echo "build completed on `date`"

artifacts:
  files:
    - app-output_sam.yaml
    - test-output_sam.yaml
  discard-paths: yes
