AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  TestFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: test_function.lambda_handler
      CodeUri: test/
      Runtime: python2.7
      Policies:
        Statement:
          - Action:
              - 'codepipeline:*'
              - 'logs:*'
            Effect: Allow
            Resource: '*'

Outputs:
  TestFunction:
    Description: Test lambda function name
    Value: !Ref TestFunction
    Export:
      Name: TestFunction